polygon.api.key=lWseFPv7rpEBrkxtc6IwaLz7QctkYduO

# PostgreSQL datasource configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/testdb
spring.datasource.username=testuser
spring.datasource.password=testpass
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

swing.threshold.1h=2
swing.threshold.15m=1
swing.threshold.1d=5
bos.threshold.1h=2
bos.threshold.15m=1
bos.threshold.1d=5
